theme: jekyll-theme-tactile
title: Rafal Urbaniak's home page
description: Mostly bayesian analyses and bayesian networks for problems I got excited about.

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
